---
title: "R Notebook"
author: Yue Gao
output: html_notebook
---

This notebook is for Data Cleaning.

Step 0: load the raw data, load the age 9 features, extract age 9 data
```{r, include=FALSE}
library(data.table)
library(stringr)
library(dmm)
library(Hmisc)

setwd("~/GitHub/Spr2017-proj5-grp3/")
load("../data/background.RData")
source("../lib/helper_data.R")
#raw=read.csv("~/Documents/FFChallenge/background.csv",header=TRUE)

features<-colnames(background)

#create codebook
codebooks<-c("child","mom","dad","teacher")
data.info<-vector()

for (i in codebooks){
feat.table<-read.csv(paste0(".../data/codebook/ff_",i,"_cb9.csv"),header=FALSE)
feat.table<-feat.table[,-1]
feat.table<-feat.table[-1,]
feat.table<-cbind(rep(i,nrow(feat.table)),feat.table)
data.info<-rbind(data.info,feat.table)
}

colnames(data.info)<-c("class","code","description")
data.info=as.data.frame(data.info)
featnum<-nrow(data.info)

extract.feature<-features %in% data.info$code  
sum(extract.feature)


extract.data<-background[,extract.feature]
extract.data<-cbind(challengeID=background[,1],extract.data)

write.csv(extract.data,file="../data/extract_data.csv")
save(data.info, file="../data/data_info.RData")
```


Step 1: clean data
```{r, message=FALSE, warning=FALSE}
#remove columns with missing values more than 80%
extract.data<-read.csv("../data/extract_data.csv")

ED<-divide.data(extract.data)
ED.categorical=ED[[1]]
ED.continuous=ED[[2]]

categorical=colnames(ED.categorical)

ED.factor=clean.factor(ED.continuous)

ED.continuous=ED.continuous[,!colnames(ED.continuous) %in% colnames(ED.factor)]
ED.continuous=clean.continuous(ED.continuous)

categorical=c(categorical,colnames(ED.factor[,grep("*isna",colnames(ED.factor))]),colnames(ED.continuous[,grep("*isna",colnames(ED.continuous))]))
#combine the data

ED.final<-cbind(ED.continuous,ED.categorical,ED.factor)

ED.final=as.data.frame(ED.final)

```



Step 2: solving missing data problem

```{r}

final.mis<-ED.final[,which(unlist(lapply(ED.final, function(x) anyNA(x))))]
missing=colnames(final.mis)

for(i in missing)
{
  ED.final[,i] = impute(ED.final[,i], fun = median)  
}

write.csv(ED.final,file="../data/NAreplaced.csv")
save(categorical, file="../data/categorical.RData")
```


#use library mice for missing data impute (didn't improve accuracy, not used)
```{r, eval=FALSE, include=FALSE}

library(mice)
imputed_Data <- mice(final.mis, m=5, maxit = 50, method = 'pmm', seed = 500)

completeData=list()

for (i in 1:5){
  completeData[[i]]<-cbind.data.frame(challengeID=ED.continuous[,1],complete(imputed_Data,i),ED.categorical)
  write.csv(completeData[[i]],file=paste0("../data/imputed",i,".csv"),row.names = FALSE)
}

```


