---
title: "R Notebook"
output: html_notebook
---



Step 0: load the raw data, load the age 9 features, extract age 9 data
```{r}
library(data.table)

load("~/GitHub/Spr2017-proj5-grp3/data/background.RData")
#raw=read.csv("~/Documents/FFChallenge/background.csv",header=TRUE)
features<-colnames(background)

codebooks<-c("child","mom","dad","teacher")
data.info<-vector()

for (i in codebooks){
feat.table<-read.csv(paste0("~/GitHub/Spr2017-proj5-grp3/data/ff_",i,"_cb9.csv"),header=FALSE)
feat.table<-feat.table[,-1]
feat.table<-feat.table[-1,]
feat.table<-cbind(rep(i,nrow(feat.table)),feat.table)
data.info<-rbind(data.info,feat.table)
}

colnames(data.info)<-c("class","code","description")
data.info=as.data.frame(data.info)
featnum<-nrow(data.info)

extract.feature<-features %in% data.info$code  
sum(extract.feature)


extract.data<-background[,extract.feature]
extract.data<-cbind(challengeID=background[,1],extract.data)

```


Step 1: solving missing data problem
```{r}

#remove columns with all NA, -9, -6, -3 values
ED<-as.data.table(extract.data)

ED=ED[,which(unlist(lapply(ED, function(x)!(all(x %in% c("-9","-8","-7","-6","-5","-3",NA)))))),with=F]

#remove rows with all NA values
#didn't remove any
#ED=ED[apply(ED[,-1],1, function(x){!(all(x %in% c("-9","-6","-3",NA)))}),]

#change from list to data frame
ED1=do.call(cbind, lapply(ED, data.frame, stringsAsFactors=FALSE))
row.names(ED1)=row.names(ED)
colnames(ED1)=colnames(ED)

#calculate the unique levels of data to split into categorical data and continuous data
ED.unique=apply(ED1, 2, function(x) uniqueN(x[! x %in% c("-9","-8","-7","-6","-5","-3",NA)]))

table(ED.unique)

#split the data
ED.categorical=ED1[,ED.unique<=15]
ED.continuous=ED1[,ED.unique>15]

#replace NA in categorical data wth -3
ED.categorical[is.na(ED.categorical)==TRUE]<-"-3"
anyNA(ED.categorical)

#add a binary indicator to indicate if NA
ED.contna=ED.continuous[,apply(ED.continuous,2, function(x) anyNA(x))]
ED.indina=ED.contna
ED.indina[is.na(ED.contna)]<-1
ED.indina[!is.na(ED.contna)]<-0
colnames(ED.indina)<-paste0(colnames(ED.contna),"_isna")

#replace NA in continuous data with median (actually can replace with any number)
library(Hmisc)
for(i in colnames(ED.contna))
{
  ED.continuous[,i] = impute(ED.continuous[,i], fun = median)  
}

anyNA(ED.continuous)

#combine the data
ED.final<-cbind(ED.continuous$challengeID,ED.categorical,ED.continuous[,-1],ED.indina)

anyNA(ED.final)

write.csv(ED.final,file="~/GitHub/Spr2017-proj5-grp3/data/NAreplaced.csv")

```



```{r}
label<-read.csv("~/Documents/FFChallenge/train.csv")

label.train<-label[,1:2]
label.train=na.omit(label.train)
trainIndex=extract.data$challengeID %in% label.train$challengeID
data.train<-extract.data[trainIndex,]
data.train<-as.data.frame(data.train)

```


```{r}
library(e1071)
library(tree)
library(caret)


#set.seed (1)
i.train = sample(1:nrow(data.train), nrow(data.train)*0.9)
dtrain=data.train[i.train,]
dtest=data.train[-i.train,]
ltrain=label.train$gpa[i.train]

dt=cbind(ltrain,dtrain[,-1])
dt=as.data.frame(dt)

tree.ff=tree(ltrain~.,dtrain)

cv.d <- cv.tree(tree.boston,FUN = prune.misclass)
prune.d <- prune.misclass(tree.boston,best = 7)
tree.pred <- predict(prune.d,subset(dtest,select=-y), type = "class")
error <- mean(tree.pred != dtest$y)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
