---
title: "Prediction Models"
author: "Jingwen Yin jy2786"
date: "April 24, 2017"
output: pdf_document
---
```{r, warning=FALSE, message=FALSE}
library(rpart)
library(party)
library(randomForest)
library(gamboostLSS)
library(e1071)
library(foreach)
library(mlbench)
library(caret)
load("../data/categorical.RData")
```

# GPA
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') #4242 1388
select <- read.csv('../data/Updated_Features/gpa_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] # 4242*64

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$gpa),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% unique(data.train[,i])))
  data.filtered[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$gpa, data.train)
colnames(data.train)[1]<-"gpa"

control <- trainControl(method="repeatedcv", number=10, repeats=3)
seed <- 7
metric <- "RMSE"
# Stochastic Gradient Boosting
set.seed(seed)
fit.gbm <- train(gpa~., data=data.train, method="gbm", metric=metric, trControl=control, verbose=FALSE)
gpa_prediction<-predict(fit.gbm, data.filtered)
```

# Grit
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/grit_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$grit),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% unique(data.train[,i])))
  data.filtered[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$grit, data.train)
colnames(data.train)[1]<-"grit"

# SVM
fit.gbm <- train(grit~., data=data.train, method="svmRadial", metric=metric, trControl=control, verbose=FALSE)
svm_prediction<-predict(fit.gbm, data.filtered)
# Random Forest
rf <- train(grit~., data=data.train, method="rf", metric=metric, trControl=control, verbose=FALSE)
rf_predictons<-predict(rf, data.filtered)
# Ensemble SVM and Random Forest
grit_prediction<-(svm_predictions+rf_predictons)/2
```

# materialHardship
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/materialHardship_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$materialHardship),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% unique(data.train[,i])))
  data.filtered[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$materialHardship, data.train)
colnames(data.train)[1]<-"materialHardship"

# Random Forest
rf <- randomForest(materialHardship~., data=data.train)
materialHardship_prediction<-predict(rf, data.filtered)
```

# eviction
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/eviction_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$eviction),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% levels(data.train[,i])))
  data.filtered[,i][id]<-sample(levels(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$eviction, data.train)
colnames(data.train)[1]<-"eviction"

# Random Forest
rf <- randomForest(factor(eviction)~., data=data.train)
eviction_prediction<-predict(rf, data.filtered)
```

# layoff
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/layoff_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$layoff),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% levels(data.train[,i])))
  data.filtered[,i][id]<-sample(levels(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$layoff, data.train)
colnames(data.train)[1]<-"layoff"

# SVM
svm_fit<-svm(factor(layoff)~., data=data.train)
layoff_prediction<-predict(svm_fit,newdata=data.filtered)
```

# jobTraining
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/jobTraining_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$jobTraining),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  data.filtered[,i]<-sapply(data.filtered[,i], factor)
  id <- which(!(data.filtered[,i] %in% levels(data.train[,i])))
  data.filtered[,i][id]<-sample(levels(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$jobTraining, data.train)
colnames(data.train)[1]<-"jobTraining"

# SVM
svm_fit<-svm(factor(jobTraining)~., data=data.train)
jobTraining_prediction<-predict(svm_fit,newdata=data.filtered)
```

```{r}
result<-data.frame(c(1:4242),gpa_prediction, grit_prediction, materialHardship_prediction, eviction_prediction, layoff_prediction, jobTraining_prediction)
colnames(result)<-colnames(label)
write.csv(result, "prediction.csv", row.names = FALSE)
```

```{r}
write.csv(gpa_prediction, "gpa.csv")
```


