---
title: "Prediction Models"
author: "Jingwen Yin jy2786"
date: "April 24, 2017"
output: pdf_document
---

# GPA
```{r, message=FALSE, warning=FALSE}
source("../lib/modelFunc.R")
load("../data/categorical.RData")
data.filtered <- read.csv('../data/NAreplaced.csv') #4242 1388
select <- read.csv('../data/Updated_Features/gpa_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$gpa),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$gpa, data.train)
colnames(data.train)[1]<-"gpa"

# create training and test data set
set.seed(123)
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-train[,1]
model_selection_con(train[,-1], test, y)
```

# Grit
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/grit_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$grit),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$grit, data.train)
colnames(data.train)[1]<-"grit"

# create training and test data set
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-train[,1]
model_selection_con(train[,-1], test, y)
```

# materialHardship
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/materialHardship_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$materialHardship),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$materialHardship, data.train)
colnames(data.train)[1]<-"materialHardship"

# create training and test data set
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-train[,1]
model_selection_con(train[,-1], test, y)
```

# eviction
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/eviction_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$eviction),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$eviction, data.train)
colnames(data.train)[1]<-"eviction"

# create training and test data set
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-factor(train[,1])
model_selection_cat(train[,-1], test, y)
```

# layoff
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/layoff_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$layoff),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$layoff, data.train)
colnames(data.train)[1]<-"layoff"

# create training and test data set
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-factor(train[,1])
model_selection_cat(train[,-1], test, y)
```

# jobTraining
```{r, message=FALSE, warning=FALSE}
data.filtered <- read.csv('../data/NAreplaced.csv') 
select <- read.csv('../data/Updated_Features/jobTraining_features.csv')
select.idx<-colnames(data.filtered) %in% as.character(select$Codes)
data.filtered <- data.filtered[,select.idx] 

label <- read.csv('../data/train.csv')
label<-label[!is.na(label$jobTraining),]
Index<-as.numeric(rownames(data.filtered))%in% label$challengeID

data.train<-data.filtered[Index,]
data.train<-as.data.frame(data.train)
cat.idx<-colnames(data.train) %in% categorical
for(i in which(cat.idx)){
  data.train[,i]<-sapply(data.train[,i], factor)
  test[,i]<-sapply(test[,i], factor)
  id <- which(!(test[,i] %in% unique(data.train[,i])))
  test[,i][id]<-sample(unique(data.train[,i]),length(id), replace = TRUE)
}
data.train<-cbind(label$jobTraining, data.train)
colnames(data.train)[1]<-"jobTraining"

# create training and test data set
train.index <- sample(1:nrow(data.train),800,replace = F)
train <- data.train[train.index,] #800*64
test <- data.train[-train.index,] #214*64

y<-factor(train[,1])
model_selection_cat(train[,-1], test, y)
```


